### ISSUE TITLE
Use one tree walk instead of two

### ISSUE THREAD

**Issue by wooorm** [zslabs/remark-relative-links#2]
Here:

https://github.com/zslabs/remark-relative-links/blob/2471cad4b1c60ada425d92f8a30591a0f9bdf295/src/index.js#L15-L16

...by calling `visit` twice, the tree gets walked twice as well.
If you’d use:

```
visit(tree, ['link', 'linkReference'], visitor);
```

...it’s a bit faster because the tree is walked once!

* For more info on using visit, see [the api description](https://github.com/syntax-tree/unist-util-visit#api)
* There are other nodes that have a URL, see more about *resource* in [the MDAST docs](https://github.com/syntax-tree/mdast#resource)

**Comment by zslabs** [comment]
Hey @wooorm thanks for the suggestion and links! Just implemented that and released a new version. Thanks again and have a great day!
